### ISSUE TITLE
es7 support

### ISSUE THREAD

**Issue by ButuzGOL** [mikach/requirejs-babel#14]
Could you please help me how can I use your plugin with es7 support ?

**Comment by mikach** [comment]
Hello!

Sorry for delay.
To use experimental es7 features, you need to enable "stage 0" support in babel. More details about stages here https://babeljs.io/docs/usage/experimental/

To enable stage0 by default, just add this line
```js
babel.options.config.stage.default = 0;
```
before line 39 in `es6.js` https://github.com/mikach/requirejs-babel/blob/master/es6.js#L39
