### ISSUE TITLE
Cannot handle dependencies that are AMD modules

### ISSUE THREAD

**Issue by kayneb** [mikach/requirejs-babel#23]
I'm trying to make use of ES6's import syntax in some of my source; however, I am consuming modules that have been defined as requirejs modules. Usage of this plugin is resulting in the definition of my depended on module to be nested within the `define` that babel puts in place.

i.e.

```
define(['exports'], function (exports) {'use strict';define(['backbone', 'jquery', 'lodash', 'react', ...
```

This results in a requirejs error:

```
Mismatched anonymous define() module
```

as it is not valid to have a `define` within a `define`.

Perhaps this plugin should have some kind of detection for whether the retrieved file is an AMD module, and if it is, do not pass the `modules: 'amd'` config to babel (so wrapping in `define(['exports'], function (exports) {}` does not happen.

**Comment by ry5n** [comment]
I had a similar problem. I managed to work around it with the require config below. The `modules` prop was the key.

```js
    //…
    exclude: ['babel'],
    pragmasOnSave: {
        'excludeBabel': true,
    },
    'config': {
        'es6': {
            'modules': undefined,
        }
    }
    //…
```

**Comment by kayneb** [comment]
This only works when you _only_ have define calls for your module. When you have a project that has a combination of both requirejs define modules, and ES6 import statement based module dependencies, you can't use this solution.

Essentially, I don't want to have to migrate the whole codebase over to ES6 imports. I want gradual adoption, and unless we have the ability to mix requirejs modules and ES6 based dependencies, that won't work.

I also don't have any idea how this can be achieved yet.

**Comment by prantlf** [comment]
If you have a mixture of AMD modules using ES2015, which do not need transpilaton, and ES6 modules using the latest JavaScript, which need transpiling, you could use the `resolveModuleSource` option to have only the ES6 modules processed by this plugin. Let's say, than the "old" modules will have the file extension `.js` and the "new" modules `.mjs`, for example:

```js
// import * from 'es5module.js'  -> define(['es5module])
// import * from 'es6module.mjs' -> define(['es6!es6module])
fileExtension: '.mjs',
resolveModuleSource: function (sourcePath, currentFile, opts) {
  if (sourcePath.indexOf('!') < 0) {
    var lengthWithoutExtension = sourcePath.length - 3
    if (sourcePath.lastIndexOf('.js') === lengthWithoutExtension) {
      return sourcePath.substr(0, lengthWithoutExtension)
    }
    --lengthWithoutExtension
    if (sourcePath.lastIndexOf('.mjs') === lengthWithoutExtension) {
      return 'es6!' + sourcePath.substr(0, lengthWithoutExtension)
    }
  }
}
```

**Comment by kayneb** [comment]
This solution would work pretty well @prantlf! That said, we've already well moved on to pure ES6 modules and webpack.
