### ISSUE TITLE
Optimize without including full Babel in the build?

### ISSUE THREAD

**Issue by RobertCZ** [mikach/requirejs-babel#3]
Hi, is it possible to optimize and get smaller build eg using babel runtime or such? Right now even smallest test files becomes over 1 mega because it includes full babel runtime

**Comment by mikach** [comment]
Thanks for submitting this issue! Must be fixed with https://github.com/mikach/requirejs-babel/commit/1133a41c6b5b461964c86d80ca1af866ee9c52fc

**Comment by mikach** [comment]
@RobertCZ Tell me if it still actual.

**Comment by RobertCZ** [comment]
That commit as far as I see allows optimized builds (I can confirm it's working OK) but there's no way to avoid having full babel inserted in the final build. That is exaggerated esp. if you don't need all of the regenerator etc. It would be better to support babel-runtime but that doesn't seem to work. In https://github.com/babel/babel/issues/638 it is recommended to use browserify/webpack - not ideal but certainly usable workaround. 

Your plugin is a life savior for people stuck on requirejs for now (thanks!), it would still be nice to support r.js but IIUC supporting r.js and babel-runtime is more on the babel side and it's not clear whether it's going to happen and when. Meanwhile workaround exists. So for me it is still valid issue but the priority is relatively low.
