### ISSUE TITLE
import without es6! prefix

### ISSUE THREAD

**Issue by djindjic** [mikach/requirejs-babel#5]
Why do we need to prefix libraries with es6! as:
>import sum from 'es6!src/sum';

I am trying to reuse regular es6 lib in requrejs apps as well as jspm/regular es6 transpiled applications. Is it possible?

**Comment by roelvanduijnhoven** [comment]
Would be useful!

**Comment by just-boris** [comment]
@djindjic @roelvanduijnhoven take a look on my fix https://github.com/mikach/requirejs-babel/pull/8.
Now you can configure babel if you want.  Look at updated demo: https://github.com/mikach/requirejs-babel/blob/master/demo/src/class.js now there is no extra prefix, but it will be added with transpilation. 
Can it solve your issue?

**Comment by djindjic** [comment]
hey @just-boris, this is exactly what I needed. thanks russian brother!  :wink:
